from __future__ import annotations

from enum import IntEnum, StrEnum


class RunStatus(StrEnum):
    RECEIVED = "RECEIVED"
    VALIDATING_CONTEXT = "VALIDATING_CONTEXT"
    RESOLVING_CONTEXT = "RESOLVING_CONTEXT"
    VALIDATING_INPUT = "VALIDATING_INPUT"
    INSPECTING_SUT = "INSPECTING_SUT"
    ANALYZING_REQUIREMENT = "ANALYZING_REQUIREMENT"
    WAITING_FOR_CLARIFICATION = "WAITING_FOR_CLARIFICATION"
    ANALYZING_RISK = "ANALYZING_RISK"
    DESIGNING_SCENARIOS = "DESIGNING_SCENARIOS"
    GENERATING_TESTS = "GENERATING_TESTS"
    CORRECTING_TESTS = "CORRECTING_TESTS"
    STATIC_VALIDATION = "STATIC_VALIDATION"
    EXECUTING_TESTS = "EXECUTING_TESTS"
    EVALUATING_EVIDENCE = "EVALUATING_EVIDENCE"
    WAITING_FOR_HUMAN_REVIEW = "WAITING_FOR_HUMAN_REVIEW"
    GENERATING_REPORT = "GENERATING_REPORT"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    POLICY_BLOCKED = "POLICY_BLOCKED"
    BUDGET_EXHAUSTED = "BUDGET_EXHAUSTED"


class RunClassification(StrEnum):
    UNCLASSIFIED = "UNCLASSIFIED"
    ACCEPTED = "ACCEPTED"
    INPUT_ERROR = "INPUT_ERROR"
    CONTEXT_ERROR = "CONTEXT_ERROR"
    WAITING_HUMAN = "WAITING_HUMAN"
    TEST_FAILURE = "TEST_FAILURE"
    TEST_ERROR = "TEST_ERROR"
    SUT_DEFECT_SUSPECTED = "SUT_DEFECT_SUSPECTED"
    POLICY_VIOLATION = "POLICY_VIOLATION"
    BUDGET_ERROR = "BUDGET_ERROR"
    PROVIDER_ERROR = "PROVIDER_ERROR"
    INFRASTRUCTURE_ERROR = "INFRASTRUCTURE_ERROR"
    CANCELLED_BY_USER = "CANCELLED_BY_USER"
    INCONCLUSIVE = "INCONCLUSIVE"


class ExitCode(IntEnum):
    SUCCESS = 0
    INVALID_INPUT_OR_CONTEXT = 2
    WAITING_HUMAN = 3
    FUNCTIONAL_FAILURE = 4
    POLICY_BLOCKED = 5
    BUDGET_EXHAUSTED = 6
    PROVIDER_OR_INFRASTRUCTURE = 7
    CANCELLED = 130


def exit_code_for(status: RunStatus, classification: RunClassification) -> ExitCode:
    if status == RunStatus.SUCCEEDED and classification == RunClassification.ACCEPTED:
        return ExitCode.SUCCESS
    if status in {RunStatus.WAITING_FOR_CLARIFICATION, RunStatus.WAITING_FOR_HUMAN_REVIEW}:
        return ExitCode.WAITING_HUMAN
    if status == RunStatus.CANCELLED:
        return ExitCode.CANCELLED
    if status == RunStatus.POLICY_BLOCKED:
        return ExitCode.POLICY_BLOCKED
    if status == RunStatus.BUDGET_EXHAUSTED:
        return ExitCode.BUDGET_EXHAUSTED
    if classification in {RunClassification.INPUT_ERROR, RunClassification.CONTEXT_ERROR}:
        return ExitCode.INVALID_INPUT_OR_CONTEXT
    if classification in {
        RunClassification.PROVIDER_ERROR,
        RunClassification.INFRASTRUCTURE_ERROR,
    }:
        return ExitCode.PROVIDER_OR_INFRASTRUCTURE
    return ExitCode.FUNCTIONAL_FAILURE
