from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass

from ..web_ui_contracts import WebUiTestPlan


@dataclass(slots=True, frozen=True)
class CompiledWebUiArtifact:
    path: str
    source: str
    sha256: str


class WebUiPlanCompiler:
    """Compile a validated declarative plan into a deterministic data-only TS module."""

    path = "generated/web-ui-plan.ts"

    @classmethod
    def compile(cls, plan: WebUiTestPlan) -> CompiledWebUiArtifact:
        plan.validate()
        payload = json.dumps(
            plan.to_dict(), ensure_ascii=True, sort_keys=True, separators=(",", ":")
        )
        source = (
            "// Generated by ASEF from WebUiTestPlan 1.0.0. Do not edit.\n"
            f"const plan = {payload};\n"
            "export default Object.freeze(plan);\n"
        )
        return CompiledWebUiArtifact(
            path=cls.path,
            source=source,
            sha256=hashlib.sha256(source.encode("utf-8")).hexdigest(),
        )
